format = "$directory $git_branch$git_commit$git_state$character"
right_format = "$cmd_duration"

add_newline = false

[character]
success_symbol = "[](bright-green)" 
error_symbol = "[](bright-red)"
vicmd_symbol = "[](purple)"

[directory]
home_symbol = " "
read_only = ""
format = "[$read_only](bright-red)[$path](bright-yellow)"

[cmd_duration]
format = "[  $duration](white)"

[package]
disabled = true

[line_break]
disabled = true

[git_state]
disabled = false

[git_commit]
disabled = false
